name: Java Add-on
version: "1.0.0"
slug: java-addon
description: Java Add-on
url: "https://github.com/andrei-vss/home-assistant-java-addon"
arch:
  - aarch64
  - amd64
init: false
map:
  - share:rw
  - addon_config:rw
  - homeassistant_config:rw
hassio_api: true